# Generated by Django 6.0.6 on 2026-07-05 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('image_0', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('text_ar', models.TextField(blank=True)),
                ('text_en', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
