# Generated by Django 6.0.6 on 2026-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
