# Generated by Django 6.0.6 on 2026-07-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
