# Generated by Django 6.0.6 on 2026-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ad_featured_until_ad_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
