# Generated by Django 6.0.6 on 2026-07-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='featured_expiry_notified',
            field=models.BooleanField(default=False),
        ),
    ]
