# Generated by Django 6.0.6 on 2026-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_ad_featured_expiry_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
